import { PieChart, Target } from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { ImpactHighlights } from "./impact-highlights"
import { formatCount, formatLabel } from "../lib/social-impact-formatters"
import { isComplete } from "../lib/social-impact-calculations"
import type { GedsiMetric, SocialImpactTotals, SocialImpactVenture } from "../types/social-impact"

export function ImpactOverviewSection({ ventures, metrics, totals }: { ventures: SocialImpactVenture[]; metrics: GedsiMetric[]; totals: SocialImpactTotals }) {
  const sectors = [...new Set(ventures.map((venture) => venture.sector).filter((sector): sector is string => Boolean(sector)))].map((sector) => ({ sector, ventures: ventures.filter((venture) => venture.sector === sector) }))
  const categories = ["GENDER", "DISABILITY", "SOCIAL_INCLUSION", "CROSS_CUTTING"] as const
  return <div className="space-y-4"><ImpactHighlights totals={totals} /><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><PieChart className="h-5 w-5 text-purple-600" />Impact by Sector</CardTitle><CardDescription>Backend-calculated beneficiaries by venture sector</CardDescription></CardHeader><CardContent className="space-y-3">{sectors.map(({ sector, ventures: sectorVentures }) => <div key={sector} className="flex min-w-0 items-center justify-between gap-3 rounded-lg border p-3"><div className="flex min-w-0 items-center gap-3"><span className="h-3 w-3 shrink-0 rounded-full bg-purple-500" /><span className="truncate font-medium">{sector}</span></div><div className="shrink-0 text-right"><p className="font-semibold">{formatCount(sectorVentures.reduce((sum, venture) => sum + (venture.totalBeneficiaries ?? 0), 0))}</p><p className="text-xs text-muted-foreground">{sectorVentures.length} ventures</p></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5 text-green-600" />GEDSI Category Progress</CardTitle><CardDescription>Verified or completed metrics by category</CardDescription></CardHeader><CardContent className="space-y-4">{categories.map((category) => { const categoryMetrics = metrics.filter((metric) => metric.category === category); const completed = categoryMetrics.filter(isComplete).length; const progress = categoryMetrics.length ? completed / categoryMetrics.length * 100 : 0; return <div key={category}><div className="flex justify-between gap-2 text-sm"><span className="font-medium">{formatLabel(category)}</span><span>{completed}/{categoryMetrics.length}</span></div><Progress value={progress} className="mt-2 h-2" /><p className="mt-1 text-xs text-muted-foreground">{progress.toFixed(0)}% completed</p></div> })}</CardContent></Card></div></div>
}
