import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { formatCount } from "../lib/social-impact-formatters"
import { gedsiCompletionRate } from "../lib/social-impact-calculations"
import type { GedsiMetric, SocialImpactTotals, SocialImpactVenture } from "../types/social-impact"

export function ImpactAnalyticsSection({ ventures, metrics, totals }: { ventures: SocialImpactVenture[]; metrics: GedsiMetric[]; totals: SocialImpactTotals }) {
  const completion = gedsiCompletionRate(metrics)
  const inclusive = ventures.filter((venture) => Boolean(venture.inclusionFocus?.trim())).length
  const inclusiveRate = ventures.length ? inclusive / ventures.length * 100 : 0
  const ranked = [...ventures].sort((a, b) => (b.socialImpactScore ?? 0) - (a.socialImpactScore ?? 0)).slice(0, 5)
  return <div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>Portfolio Social Performance</CardTitle><CardDescription>Overall social impact performance metrics</CardDescription></CardHeader><CardContent className="space-y-5">{[["GEDSI Completion Rate", `${completion.toFixed(0)}%`, completion], ["Inclusive Ventures", `${inclusive}/${ventures.length}`, inclusiveRate]].map(([label, value, progress]) => <div key={label as string}><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{label}</span><span className="text-2xl font-semibold">{value}</span></div><Progress value={progress as number} className="mt-2 h-2" /></div>)}<div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">Average Beneficiaries per Venture</span><span className="text-2xl font-semibold">{formatCount(totals.totalBeneficiaries / Math.max(ventures.length, 1))}</span></div></CardContent></Card><Card><CardHeader><CardTitle>Top Impact Drivers</CardTitle><CardDescription>Ranked by authoritative social impact score</CardDescription></CardHeader><CardContent className="space-y-3">{ranked.map((venture, index) => <div key={venture.id} className="flex min-w-0 items-center justify-between gap-3 rounded-lg border p-3"><div className="flex min-w-0 items-center gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-purple-100 text-sm font-bold text-purple-600">{index + 1}</span><div className="min-w-0"><p className="truncate font-medium">{venture.name || "Unnamed venture"}</p><p className="truncate text-sm text-muted-foreground">{venture.sector || "Uncategorised"}</p></div></div><div className="shrink-0 text-right"><p className="font-semibold text-purple-600">{venture.socialImpactScore ?? 0}</p><p className="text-xs text-muted-foreground">Impact score</p></div></div>)}</CardContent></Card></div>
}
