import { Building2, Calendar, Edit, Eye, MapPin, MoreHorizontal, Share2, Users } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import type { CalendarEvent } from "../types/calendar"
import { EventTypeBadge, EventTypeIcon, PriorityBadge, StatusBadge } from "../lib/calendar-display-utils"

export function CalendarEventCard({ event, compact = false }: { event: CalendarEvent; compact?: boolean }) {
  return <Card className="min-w-0 transition-shadow hover:shadow-md"><CardContent className={compact ? "p-4" : "p-4 sm:p-6"}><div className="flex min-w-0 flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 flex-1 gap-3"><EventTypeIcon type={event.type} className="mt-1 h-4 w-4 shrink-0" /><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><h3 className="min-w-0 break-words text-base font-semibold sm:text-lg">{event.title}</h3><EventTypeBadge type={event.type} /><PriorityBadge priority={event.priority} /><StatusBadge status={event.status} /></div>{!compact && event.description && <p className="mb-3 break-words text-sm text-muted-foreground sm:text-base">{event.description}</p>}<div className="grid min-w-0 gap-2 text-sm md:grid-cols-2 lg:grid-cols-4"><Info icon={Calendar} text={`${event.startDate} ${event.startTime}${event.endTime ? ` - ${event.endTime}` : ""}`} /><Info icon={MapPin} text={event.location || "No location"} /><Info icon={Users} text={`${event.attendees.length} attendees`} />{event.company && <Info icon={Building2} text={event.company} />}</div>{!compact && event.notes && <p className="mt-3 break-words rounded-lg bg-muted p-3 text-sm text-muted-foreground"><strong>Notes:</strong> {event.notes}</p>}</div></div><div className="flex shrink-0 items-center justify-end gap-1 border-t pt-2 sm:border-0 sm:pt-0">{[[Eye,"View"],[Edit,"Edit"],[Share2,"Share"],[MoreHorizontal,"More options"]].map(([Icon,label]) => <Button key={label as string} variant="ghost" size="icon" aria-label={`${label} ${event.title}`}><Icon className="h-4 w-4" /></Button>)}</div></div></CardContent></Card>
}
function Info({ icon: Icon, text }: { icon: typeof Calendar; text: string }) { return <div className="flex min-w-0 items-start gap-2"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" /><span className="min-w-0 break-words">{text}</span></div> }
