import { addMonths, startOfMonth } from "date-fns"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import type { CalendarEvent } from "../types/calendar"
import { dateKey, getMonthDays, groupEventsByDay, isToday, monthLabel } from "../lib/calendar-date-utils"

export function CalendarMonthView({ events, month, setMonth }: { events: CalendarEvent[]; month: Date; setMonth(value: Date): void }) {
  const grouped = groupEventsByDay(events)
  return <Card className="min-w-0"><CardHeader><CardTitle>Calendar View</CardTitle><CardDescription>Monthly calendar view of all events</CardDescription></CardHeader><CardContent className="min-w-0 px-2 sm:px-6"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="grid grid-cols-3 gap-2"><Button variant="outline" size="sm" onClick={() => setMonth(addMonths(month, -1))}>Prev</Button><Button variant="outline" size="sm" onClick={() => setMonth(startOfMonth(new Date()))}>Today</Button><Button variant="outline" size="sm" onClick={() => setMonth(addMonths(month, 1))}>Next</Button></div><div className="text-center text-sm font-medium text-muted-foreground" aria-live="polite">{monthLabel(month)}</div></div><div className="grid grid-cols-7 gap-0.5 text-[10px] font-medium text-muted-foreground sm:gap-2 sm:text-xs">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((day) => <div key={day} className="text-center"><span className="sm:hidden">{day[0]}</span><span className="hidden sm:inline">{day}</span></div>)}</div><div className="mt-2 grid grid-cols-7 gap-0.5 sm:gap-2">{getMonthDays(month).map(({ date, inMonth }) => { const dayEvents = grouped.get(dateKey(date)) ?? []; return <div key={dateKey(date)} className={`min-w-0 rounded border p-1 min-h-14 sm:min-h-24 sm:p-2 ${inMonth ? "bg-background" : "bg-muted/50"} ${isToday(date) ? "ring-2 ring-blue-500" : ""}`}><div className="mb-1 flex items-center justify-between gap-0.5"><span className={`text-[10px] sm:text-xs ${inMonth ? "" : "text-muted-foreground"}`}>{date.getDate()}</span>{dayEvents.length > 0 && <Badge variant="secondary" className="hidden h-4 px-1 text-[9px] min-[375px]:inline-flex sm:text-[10px]">{dayEvents.length}</Badge>}</div><div className="space-y-1">{dayEvents.slice(0, 3).map((event) => <div key={event.id} title={event.title} className="h-1.5 overflow-hidden rounded bg-blue-200 text-[0] text-blue-700 sm:h-auto sm:truncate sm:px-1 sm:py-0.5 sm:text-[11px]">{event.title}</div>)}{dayEvents.length > 3 && <div className="hidden text-[11px] text-muted-foreground sm:block">+{dayEvents.length - 3} more</div>}</div></div> })}</div></CardContent></Card>
}
