import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Progress } from "@/components/ui/progress"
import { formatFinancialValue, parseFinancialAmount } from "@/lib/fund-management/calculations"
import { getFundStatusBadge } from "@/lib/fund-management/status"
import type { Fund } from "@/types/fund-management"

export function FundDetailsDialog({ open, onOpenChange, fund }: { open: boolean; onOpenChange: (open: boolean) => void; fund: Fund | null }) {
  const committed = parseFinancialAmount(fund?.committedCapital)
  const called = parseFinancialAmount(fund?.calledCapital)
  const calledPercentage = committed > 0 ? Math.min(100, Math.max(0, (called / committed) * 100)) : 0
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] w-[95vw] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle className="break-words">{fund?.name ?? "Fund details"}</DialogTitle><DialogDescription>Performance, strategy, and operating information</DialogDescription></DialogHeader>{fund && <div className="space-y-6"><div className="flex flex-wrap items-center gap-2">{getFundStatusBadge(fund.status)}<span className="text-sm text-muted-foreground">{fund.vintage} vintage · {fund.fundType} · {fund.geography}</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Committed", formatFinancialValue(fund.committedCapital)], ["Called", formatFinancialValue(fund.calledCapital)], ["Distributed", formatFinancialValue(fund.distributedCapital)], ["Net asset value", formatFinancialValue(fund.netAssetValue)], ["IRR", `${fund.irr.toFixed(1)}%`], ["TVPI", `${fund.tvpi.toFixed(2)}x`], ["DPI", `${fund.dpi.toFixed(2)}x`], ["Dry powder", formatFinancialValue(fund.dryPowder)]].map(([label, value]) => <div key={label} className="rounded-lg border bg-muted/30 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-lg font-semibold">{value}</p></div>)}</div><section><div className="mb-2 flex justify-between text-sm"><span>Capital called</span><span>{calledPercentage.toFixed(1)}%</span></div><Progress value={calledPercentage} /></section><div className="grid gap-6 sm:grid-cols-2"><section className="space-y-2 text-sm"><h3 className="font-semibold">Fund terms</h3><p>Investment period: {fund.investmentPeriod}</p><p>Fund term: {fund.fundTerm}</p><p>Management fee: {fund.managementFee}%</p><p>Carried interest: {fund.carriedInterest}%</p></section><section className="min-w-0 space-y-2 text-sm"><h3 className="font-semibold">Administration</h3><p className="break-words">Manager: {fund.fundManager}</p><p className="break-words">Administrator: {fund.fundAdmin}</p><p className="break-words">Auditor: {fund.auditor}</p><p className="break-words">Legal counsel: {fund.legalCounsel}</p></section></div></div>}</DialogContent></Dialog>
}
