import { AlertCircle, Download, Globe, Lightbulb, Share2, Shield, Sparkles, Zap } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { SECTORS } from "@/lib/investment-rounds/constants"
import { amountInMillions, percentage, timelineRounds, topGedsiRounds } from "@/lib/investment-rounds/calculations"
import type { InvestmentRound, InvestmentRoundSummary, RiskLevel } from "@/lib/investment-rounds/types"
import { gedsiScoreClass, RiskBadge, RiskIcon, StatusBadge } from "./round-presentation"

export function GedsiImpactPanel({ rounds, summary: s }: { rounds: InvestmentRound[]; summary: InvestmentRoundSummary }) {
  const performance = [["Average GEDSI Score", s.avgGedsiScore.toFixed(0), gedsiScoreClass(s.avgGedsiScore)], ["Average Impact Score", s.avgImpactScore.toFixed(0), "text-blue-600"], ["Average Sustainability Score", s.avgSustainabilityScore.toFixed(0), "text-green-600"], ["Women-Led Rounds", `${s.womenLedRounds} (${s.womenLedPercentage.toFixed(0)}%)`, "text-purple-600"], ["Disability-Inclusive", `${s.disabilityInclusiveRounds} (${s.disabilityInclusivePercentage.toFixed(0)}%)`, "text-indigo-600"]]
  const impact = [["Total Jobs Created", s.totalJobsCreated, "text-green-600"], ["Communities Served", s.totalCommunitiesServed, "text-blue-600"], ["Carbon Reduction", `${s.totalCarbonReduction.toFixed(1)}t CO2`, "text-green-600"], ["Avg Women Leadership", `${s.avgWomenLeadership.toFixed(0)}%`, "text-purple-600"]]
  const list = (items: (string | number)[][]) => <div className="space-y-4">{items.map(([label, value, color]) => <div key={label} className="flex items-center justify-between rounded-lg border p-3"><span>{label}</span><span className={`text-lg font-bold ${color}`}>{value}</span></div>)}</div>
  return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>GEDSI Performance Overview</CardTitle></CardHeader><CardContent>{list(performance)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Globe className="h-5 w-5" />Impact Metrics Summary</CardTitle></CardHeader><CardContent>{list(impact)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Top GEDSI Performers</CardTitle></CardHeader><CardContent><div className="space-y-4">{topGedsiRounds(rounds).map((round) => <div key={round.id} className="flex items-center justify-between rounded-lg border p-3"><div><div className="font-medium">{round.company}</div><div className="text-sm text-muted-foreground">{round.sector} • {round.inclusionFocus}</div><div className="mt-1 flex gap-1">{round.founderType.slice(0, 3).map((type) => <Badge key={type} variant="outline" className="text-xs">{type.replace("-", " ")}</Badge>)}</div></div><div className="text-right"><div className={`text-lg font-bold ${gedsiScoreClass(round.gedsiScore)}`}>{round.gedsiScore}</div><div className="text-sm text-muted-foreground">I:{round.impactScore} S:{round.sustainabilityScore}</div></div></div>)}</div></CardContent></Card>
  </div>
}

export function AIInsightsPanel({ rounds }: { rounds: InvestmentRound[] }) {
  return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Shield className="h-5 w-5" />Risk Distribution</CardTitle></CardHeader><CardContent><div className="space-y-4">{(["low", "medium", "high"] as RiskLevel[]).map((level) => { const count = rounds.filter((round) => round.aiInsights.riskLevel === level).length; return <div key={level} className="flex items-center justify-between rounded-lg border p-3"><div className="flex items-center gap-2"><RiskIcon level={level} /><span className="capitalize">{level} Risk</span></div><div className="text-right"><div className="font-medium">{count}</div><div className="text-sm text-muted-foreground">({percentage(count, rounds.length).toFixed(1)}%)</div></div></div> })}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Lightbulb className="h-5 w-5" />AI Recommendations</CardTitle></CardHeader><CardContent><div className="space-y-3">{rounds.slice(0, 3).map((round) => <div key={round.id} className="rounded-lg border p-3"><div className="mb-1 text-sm font-medium">{round.company}</div><p className="text-xs text-muted-foreground">{round.aiInsights.recommendation.substring(0, 80)}...</p></div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5" />Key Strengths</CardTitle></CardHeader><CardContent><div className="space-y-2">{Array.from(new Set(rounds.flatMap((round) => round.aiInsights.keyStrengths))).slice(0, 8).map((strength) => <Badge key={strength} variant="outline" className="text-xs">{strength}</Badge>)}</div></CardContent></Card></div>
    <Card><CardHeader><CardTitle>AI Analysis by Round</CardTitle></CardHeader><CardContent><div className="space-y-4">{rounds.map((round) => <div key={round.id} className="rounded-lg border p-4"><div className="mb-3 flex items-center justify-between"><div><h4 className="font-medium">{round.company} - {round.roundType}</h4><p className="text-sm text-muted-foreground">{round.inclusionFocus}</p></div><div className="flex items-center gap-2"><RiskIcon level={round.aiInsights.riskLevel} /><RiskBadge level={round.aiInsights.riskLevel} /></div></div><div className="grid gap-4 md:grid-cols-2"><InsightList title="Key Strengths" icon={<Sparkles className="h-4 w-4" />} items={round.aiInsights.keyStrengths} /><InsightList title="Areas for Improvement" icon={<AlertCircle className="h-4 w-4" />} items={round.aiInsights.areasForImprovement} secondary /></div><div className="mt-3 rounded-lg bg-muted p-3"><p className="text-sm">{round.aiInsights.recommendation}</p></div></div>)}</div></CardContent></Card>
  </div>
}

function InsightList({ title, icon, items, secondary = false }: { title: string; icon: React.ReactNode; items: string[]; secondary?: boolean }) { return <div><h5 className="mb-2 flex items-center gap-1 text-sm font-medium">{icon}{title}</h5><div className="space-y-1">{items.map((item) => <Badge key={item} variant={secondary ? "secondary" : "outline"} className="mr-1 text-xs">{item}</Badge>)}</div></div> }

export function InvestmentTimeline({ rounds }: { rounds: InvestmentRound[] }) { const ordered = timelineRounds(rounds); return <Card><CardHeader><CardTitle>Investment Timeline</CardTitle><CardDescription>Timeline view of investment rounds and key milestones</CardDescription></CardHeader><CardContent><div className="space-y-6">{ordered.map((round, index) => <div key={round.id} className="flex items-start gap-4"><div className="flex flex-col items-center"><div className="h-4 w-4 rounded-full bg-blue-500" />{index < ordered.length - 1 && <div className="mt-2 h-16 w-0.5 bg-gray-200" />}</div><div className="flex-1 space-y-2"><div className="flex items-center justify-between"><h4 className="font-medium">{round.company} - {round.roundType}</h4><div className="flex items-center gap-2"><StatusBadge status={round.status} /><span className="text-sm text-muted-foreground">{round.closingDate}</span></div></div><p className="text-sm text-muted-foreground">Target: {round.targetAmount} | Raised: {round.raisedAmount} | Lead: {round.leadInvestor}</p><div className="flex items-center gap-4 text-sm text-muted-foreground"><span>Valuation: {round.valuation}</span><span>Ownership: {round.ownership}%</span><span>{round.participants.length} participants</span></div></div></div>)}</div></CardContent></Card> }

export function InvestmentAnalytics({ rounds }: { rounds: InvestmentRound[] }) {
  const investors = Array.from(new Set(rounds.map((round) => round.leadInvestor)))
  return <Card><CardHeader><CardTitle>Investment Analytics</CardTitle><CardDescription>Detailed analytics and insights on investment rounds</CardDescription></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2"><div className="space-y-4"><h4 className="font-medium">Top Lead Investors</h4>{investors.map((investor) => { const items = rounds.filter((round) => round.leadInvestor === investor); const total = items.reduce((sum, round) => sum + amountInMillions(round.targetAmount), 0); return <div key={investor} className="flex items-center justify-between rounded-lg border p-3"><span className="font-medium">{investor}</span><div className="text-right"><div className="font-medium">${total.toFixed(1)}M</div><div className="text-sm text-muted-foreground">{items.length} rounds</div></div></div> })}</div><div className="space-y-4"><h4 className="font-medium">Sector Performance</h4>{SECTORS.slice(0, 5).map((sector) => { const items = rounds.filter((round) => round.sector === sector); const average = items.length ? items.reduce((sum, round) => sum + round.gedsiScore, 0) / items.length : 0; return <div key={sector} className="flex items-center justify-between rounded-lg border p-3"><span className="font-medium">{sector}</span><div className="text-right"><div className={`font-medium ${gedsiScoreClass(average)}`}>GEDSI: {average.toFixed(0)}</div><div className="text-sm text-muted-foreground">{items.length} rounds</div></div></div> })}</div></div></CardContent></Card>
}

export function RoundDocumentsPanel() { return <Card><CardHeader><CardTitle>Round Documents</CardTitle><CardDescription>Manage documents related to investment rounds</CardDescription></CardHeader><CardContent><div className="space-y-4"><div className="flex items-center gap-4"><Button><Download className="mr-2 h-4 w-4" />Upload Documents</Button><Button variant="outline"><Share2 className="mr-2 h-4 w-4" />Share All</Button></div><div className="py-12 text-center text-muted-foreground"><Zap className="mx-auto mb-4 h-12 w-12 opacity-50" /><p>No documents uploaded yet</p><p className="text-sm">Upload documents to track round progress</p></div></div></CardContent></Card> }
