// Frontend demonstration data.
// Replace with live Capital Facilitation API data when backend integration is available.
import type {
  CapitalFacilitationRecord,
  CapitalFacilitationSummaryCard,
  CapitalInvestorRecord,
  DueDiligenceRecord,
  DueDiligenceSummaryCard,
  FundingPipelineRecord,
  FundingPipelineStage,
  InvestmentReadinessRecord,
  CapitalRequestRecord,
} from "../types"

export const capitalSummaryDemo: CapitalFacilitationSummaryCard[] = [
  { label: "Active Capital Requests", value: "8", supportingText: "Ventures currently seeking funding" },
  { label: "Total Capital Required", value: "$4.8M", supportingText: "Combined funding requirement" },
  { label: "Capital Secured", value: "$2.9M", supportingText: "Committed and confirmed funding" },
  { label: "Remaining Funding Gap", value: "$1.9M", supportingText: "Capital still required" },
]

export const capitalVenturesDemo: CapitalFacilitationRecord[] = [
  {
    id: "cf-eco-harvest",
    ventureName: "EcoHarvest Technologies",
    fundingStage: "Seed",
    capitalRequired: 750_000,
    capitalSecured: 450_000,
    fundingGap: 300_000,
    progress: 60,
    investorReadiness: "Ready",
    status: "Investor Ready",
  },
  {
    id: "cf-healthbridge-ai",
    ventureName: "HealthBridge AI",
    fundingStage: "Series A",
    capitalRequired: 1_200_000,
    capitalSecured: 900_000,
    fundingGap: 300_000,
    progress: 75,
    investorReadiness: "Ready",
    status: "Due Diligence",
  },
  {
    id: "cf-greenloop-energy",
    ventureName: "GreenLoop Energy",
    fundingStage: "Seed",
    capitalRequired: 600_000,
    capitalSecured: 240_000,
    fundingGap: 360_000,
    progress: 40,
    investorReadiness: "In Review",
    status: "Fundraising",
  },
  {
    id: "cf-agriconnect",
    ventureName: "AgriConnect",
    fundingStage: "Pre-Seed",
    capitalRequired: 350_000,
    capitalSecured: 100_000,
    fundingGap: 250_000,
    progress: 29,
    investorReadiness: "Preparing",
    status: "Preparing",
  },
  {
    id: "cf-circularworks",
    ventureName: "CircularWorks",
    fundingStage: "Series A",
    capitalRequired: 1_100_000,
    capitalSecured: 1_100_000,
    fundingGap: 0,
    progress: 100,
    investorReadiness: "Ready",
    status: "Funded",
  },
  {
    id: "cf-impactpay",
    ventureName: "ImpactPay",
    fundingStage: "Seed",
    capitalRequired: 800_000,
    capitalSecured: 420_000,
    fundingGap: 380_000,
    progress: 53,
    investorReadiness: "Ready",
    status: "Investor Ready",
  },
]

export const fundingStageOptions = ["All Stages", "Pre-Seed", "Seed", "Series A", "Series B", "Growth"]

export const fundingStatusOptions = [
  "All Statuses",
  "Preparing",
  "Investor Ready",
  "Fundraising",
  "Due Diligence",
  "Funded",
]

export const capitalRequestsDemo: CapitalRequestRecord[] = [
  {
    id: "req-eco-harvest",
    ventureName: "EcoHarvest Technologies",
    requestType: "Growth Capital",
    amountRequested: "$750K",
    fundingStage: "Seed",
    targetClose: "30 Sep 2026",
    priority: "High",
    status: "Open",
  },
  {
    id: "req-healthbridge-ai",
    ventureName: "HealthBridge AI",
    requestType: "Series A Raise",
    amountRequested: "$1.2M",
    fundingStage: "Series A",
    targetClose: "15 Oct 2026",
    priority: "High",
    status: "Investor Review",
  },
  {
    id: "req-greenloop-energy",
    ventureName: "GreenLoop Energy",
    requestType: "Expansion Capital",
    amountRequested: "$600K",
    fundingStage: "Seed",
    targetClose: "31 Oct 2026",
    priority: "Medium",
    status: "Fundraising",
  },
  {
    id: "req-agriconnect",
    ventureName: "AgriConnect",
    requestType: "Pre-Seed Raise",
    amountRequested: "$350K",
    fundingStage: "Pre-Seed",
    targetClose: "15 Nov 2026",
    priority: "Medium",
    status: "Preparing",
  },
  {
    id: "req-circularworks",
    ventureName: "CircularWorks",
    requestType: "Series A Raise",
    amountRequested: "$1.1M",
    fundingStage: "Series A",
    targetClose: "Closed",
    priority: "Low",
    status: "Closed",
  },
  {
    id: "req-impactpay",
    ventureName: "ImpactPay",
    requestType: "Growth Capital",
    amountRequested: "$800K",
    fundingStage: "Seed",
    targetClose: "20 Nov 2026",
    priority: "High",
    status: "Investor Review",
  },
]

export const requestStatusOptions = ["All Statuses", "Open", "Preparing", "Fundraising", "Investor Review", "Closed"]

export const capitalInvestorsDemo: CapitalInvestorRecord[] = [
  {
    id: "inv-horizon-impact",
    investorName: "Horizon Impact Ventures",
    investorType: "Impact VC",
    sectorInterest: "Climate & Sustainability",
    preferredStage: "Seed / Series A",
    indicativeInterest: "$500K",
    engagementStatus: "Due Diligence",
  },
  {
    id: "inv-pacific-growth",
    investorName: "Pacific Growth Partners",
    investorType: "Venture Capital",
    sectorInterest: "Technology",
    preferredStage: "Series A",
    indicativeInterest: "$750K",
    engagementStatus: "Interested",
  },
  {
    id: "inv-inclusive-capital",
    investorName: "Inclusive Capital Fund",
    investorType: "Impact Fund",
    sectorInterest: "Social Enterprise",
    preferredStage: "Pre-Seed / Seed",
    indicativeInterest: "$300K",
    engagementStatus: "Initial Discussion",
  },
  {
    id: "inv-greenfuture",
    investorName: "GreenFuture Ventures",
    investorType: "Climate Fund",
    sectorInterest: "Clean Energy",
    preferredStage: "Seed",
    indicativeInterest: "$400K",
    engagementStatus: "Investor Ready",
  },
]

export const fundingPipelineStagesDemo: FundingPipelineStage[] = [
  { label: "Capital Preparation", value: "2 Ventures" },
  { label: "Investor Ready", value: "3 Ventures" },
  { label: "Investor Engagement", value: "4 Ventures" },
  { label: "Due Diligence", value: "2 Ventures" },
  { label: "Term Sheet", value: "1 Venture" },
  { label: "Funded", value: "1 Venture" },
]

export const fundingPipelineDemo: FundingPipelineRecord[] = [
  {
    id: "fp-eco-harvest",
    ventureName: "EcoHarvest Technologies",
    currentStage: "Investor Engagement",
    nextStep: "Schedule investor pitch",
    fundingTarget: "$750K",
    probability: 65,
    status: "On Track",
  },
  {
    id: "fp-healthbridge-ai",
    ventureName: "HealthBridge AI",
    currentStage: "Due Diligence",
    nextStep: "Complete legal review",
    fundingTarget: "$1.2M",
    probability: 75,
    status: "On Track",
  },
  {
    id: "fp-greenloop-energy",
    ventureName: "GreenLoop Energy",
    currentStage: "Investor Engagement",
    nextStep: "Follow up with GreenFuture Ventures",
    fundingTarget: "$600K",
    probability: 45,
    status: "At Risk",
  },
  {
    id: "fp-agriconnect",
    ventureName: "AgriConnect",
    currentStage: "Capital Preparation",
    nextStep: "Finalise pitch deck",
    fundingTarget: "$350K",
    probability: 30,
    status: "On Track",
  },
  {
    id: "fp-circularworks",
    ventureName: "CircularWorks",
    currentStage: "Funded",
    nextStep: "Onboard investor reporting",
    fundingTarget: "$1.1M",
    probability: 100,
    status: "Complete",
  },
  {
    id: "fp-impactpay",
    ventureName: "ImpactPay",
    currentStage: "Investor Ready",
    nextStep: "Distribute data room access",
    fundingTarget: "$800K",
    probability: 55,
    status: "On Track",
  },
]

export const dueDiligenceSummaryDemo: DueDiligenceSummaryCard[] = [
  { label: "In Due Diligence", value: "3" },
  { label: "Documents Complete", value: "8 / 12" },
  { label: "Pending Reviews", value: "4" },
  { label: "Ready for Decision", value: "2" },
]

export const dueDiligenceDemo: DueDiligenceRecord[] = [
  {
    id: "dd-eco-harvest",
    ventureName: "EcoHarvest Technologies",
    financialReview: "Complete",
    legalReview: "In Review",
    businessModel: "Complete",
    impactAssessment: "Complete",
    documentation: "In Review",
    overallStatus: "In Review",
  },
  {
    id: "dd-healthbridge-ai",
    ventureName: "HealthBridge AI",
    financialReview: "Complete",
    legalReview: "Complete",
    businessModel: "Complete",
    impactAssessment: "In Review",
    documentation: "Complete",
    overallStatus: "Ready for Decision",
  },
  {
    id: "dd-greenloop-energy",
    ventureName: "GreenLoop Energy",
    financialReview: "In Review",
    legalReview: "Pending",
    businessModel: "In Review",
    impactAssessment: "Pending",
    documentation: "Pending",
    overallStatus: "Attention Required",
  },
  {
    id: "dd-circularworks",
    ventureName: "CircularWorks",
    financialReview: "Complete",
    legalReview: "Complete",
    businessModel: "Complete",
    impactAssessment: "Complete",
    documentation: "Complete",
    overallStatus: "Ready for Decision",
  },
]

export const investmentReadinessDemo: InvestmentReadinessRecord[] = [
  {
    id: "ir-eco-harvest",
    ventureName: "EcoHarvest Technologies",
    pitchDeck: "Complete",
    financialModel: "Complete",
    dataRoom: "Complete",
    legal: "In Review",
    readinessScore: 90,
    status: "Investor Ready",
  },
  {
    id: "ir-healthbridge-ai",
    ventureName: "HealthBridge AI",
    pitchDeck: "Complete",
    financialModel: "Complete",
    dataRoom: "Complete",
    legal: "Complete",
    readinessScore: 95,
    status: "Investor Ready",
  },
  {
    id: "ir-greenloop-energy",
    ventureName: "GreenLoop Energy",
    pitchDeck: "Complete",
    financialModel: "In Review",
    dataRoom: "Pending",
    legal: "Pending",
    readinessScore: 65,
    status: "Preparing",
  },
  {
    id: "ir-agriconnect",
    ventureName: "AgriConnect",
    pitchDeck: "In Review",
    financialModel: "Pending",
    dataRoom: "Pending",
    legal: "Pending",
    readinessScore: 40,
    status: "Preparing",
  },
  {
    id: "ir-circularworks",
    ventureName: "CircularWorks",
    pitchDeck: "Complete",
    financialModel: "Complete",
    dataRoom: "Complete",
    legal: "Complete",
    readinessScore: 100,
    status: "Investor Ready",
  },
  {
    id: "ir-impactpay",
    ventureName: "ImpactPay",
    pitchDeck: "Complete",
    financialModel: "Complete",
    dataRoom: "In Review",
    legal: "In Review",
    readinessScore: 80,
    status: "Investor Ready",
  },
]
