import { REPORT_SECTION_OPTIONS } from "../constants/due-diligence.constants"
import type { ReportSections, ReportType } from "../types/due-diligence.types"

export function getDefaultReportSections(reportType: string): ReportSections {
  const defaultSections: ReportSections = {}
  REPORT_SECTION_OPTIONS[reportType as ReportType]?.forEach((section) => {
    defaultSections[section.id] = section.default
  })
  return defaultSections
}

export function generateCustomizedReportContent(
  reportType: string,
  sections: ReportSections,
  venture: string,
  reportFormat: string
): string {
  const selectedSections = Object.keys(sections).filter((key) => sections[key])
  const ventureFilter = venture === "all" ? "All Ventures" : venture

  let content = `MIV PLATFORM - ${reportType.toUpperCase()} DUE DILIGENCE REPORT (CUSTOMIZED)
Generated: ${new Date().toLocaleDateString()}
Venture Scope: ${ventureFilter}
Selected Sections: ${selectedSections.join(", ")}
Format: ${reportFormat.toUpperCase()}

`

  selectedSections.forEach((sectionId) => {
    switch (sectionId) {
      case "executive_summary":
        content += `EXECUTIVE SUMMARY
================
This ${reportType} due diligence report provides targeted analysis based on your selected criteria.
Focus areas include ${selectedSections.length} key sections for comprehensive assessment.

`
        break
      case "financial_health":
        content += `FINANCIAL HEALTH ANALYSIS
========================
â€¢ Revenue Growth: 45% YoY growth with strong fundamentals
â€¢ Cash Flow: Positive operating cash flow for 8 consecutive quarters
â€¢ Burn Rate: Efficient capital utilization with 18-month runway
â€¢ Unit Economics: LTV/CAC ratio of 4.2x (industry benchmark: 3x)

`
        break
      case "gedsi_financial":
        content += `GEDSI FINANCIAL IMPACT
=====================
â€¢ Women Leadership ROI: 23% higher productivity metrics
â€¢ Inclusive Hiring Investment: $75K annual D&I program budget
â€¢ Accessibility ROI: 15% revenue increase from accessible design
â€¢ Rural Market Revenue: 65% of total revenue from underserved areas

`
        break
      case "investment_readiness":
        content += `INVESTMENT READINESS
===================
â€¢ Financial Model: 5-year projections with sensitivity analysis
â€¢ Audit Status: Clean opinions from reputable accounting firm
â€¢ Legal Structure: Investment-ready corporate structure
â€¢ Due Diligence Materials: Complete data room prepared

`
        break
      case "risk_assessment":
        content += `RISK ASSESSMENT
==============
â€¢ Market Risk: Medium - competitive but differentiated positioning
â€¢ Financial Risk: Low - strong unit economics and cash management
â€¢ Operational Risk: Low - experienced team with proven execution
â€¢ Technology Risk: Low - modern, scalable architecture

`
        break
      case "recommendations":
        content += `RECOMMENDATIONS
==============
1. Proceed with investment - meets all MIV criteria
2. Implement quarterly impact reporting
3. Establish GEDSI monitoring dashboard
4. Consider follow-on funding in 18-24 months

`
        break
      case "iris_metrics":
        content += `IRIS+ METRICS ALIGNMENT
======================
â€¢ OI.1 (Jobs Created): 150 direct jobs, 300 indirect jobs
â€¢ OI.2 (Income): $2.5M revenue supporting local economies
â€¢ OI.3 (Financial Services): 25,000 underbanked customers served
â€¢ PI.1 (Gender): 60% women in leadership positions
â€¢ PI.2 (Youth): 40% employees under 30 years old

`
        break
      default:
        content += `${sectionId.replace("_", " ").toUpperCase()}
${"=".repeat(sectionId.length + 1)}
Detailed analysis for ${sectionId.replace("_", " ")} section.

`
    }
  })

  content += `
Report customized by: ${selectedSections.length} selected sections
Generated by: MIV AI Analysis Engine
Contact: reports@miv.org
`

  return content
}

export function downloadReport(content: string, filename: string, reportFormat: string): void {
  const blob = new Blob([content], { type: reportFormat === "pdf" ? "application/pdf" : "text/plain" })
  const url = window.URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  window.URL.revokeObjectURL(url)
}

export function generateFinancialReport(): string {
  return `MIV PLATFORM - FINANCIAL DUE DILIGENCE REPORT
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
================
This financial due diligence report provides a comprehensive analysis of the venture's financial health, 
revenue model, and investment readiness based on MIV's impact investing criteria.

FINANCIAL HEALTH ANALYSIS
========================
â€¢ Revenue Growth: Strong 45% YoY growth demonstrated
â€¢ Burn Rate: Sustainable burn rate with 18-month runway
â€¢ Unit Economics: Positive contribution margins
â€¢ Financial Controls: Adequate accounting systems in place

GEDSI FINANCIAL IMPACT
=====================
â€¢ Women Leadership Financial Performance: Above industry average
â€¢ Inclusive Hiring ROI: 23% improvement in productivity metrics
â€¢ Disability Inclusion Investment: $50K annual accessibility improvements
â€¢ Rural Market Penetration: 65% of revenue from underserved communities

INVESTMENT READINESS
===================
â€¢ Financial Projections: Comprehensive 5-year model provided
â€¢ Audit Status: Clean audit for last 2 years
â€¢ Legal Structure: Appropriate corporate structure for investment
â€¢ Tax Compliance: All filings current and compliant

RISK ASSESSMENT
==============
â€¢ Market Risk: Medium - competitive landscape
â€¢ Financial Risk: Low - strong unit economics
â€¢ Operational Risk: Low - experienced management team
â€¢ Regulatory Risk: Medium - evolving regulatory environment

RECOMMENDATIONS
==============
1. Proceed with investment - strong financial fundamentals
2. Request quarterly financial reporting post-investment
3. Implement enhanced GEDSI financial tracking
4. Consider board seat for financial oversight

IRIS+ METRICS ALIGNMENT
======================
â€¢ OI.1 (Revenue): $2.5M projected next 12 months
â€¢ OI.2 (Jobs): 150 direct jobs, 60% women
â€¢ OI.3 (Financial Inclusion): 25,000 underbanked customers served

This analysis supports the investment recommendation with strong confidence in financial returns and impact outcomes.

Report prepared by: MIV AI Analysis Engine
Contact: reports@miv.org
`
}

export function generateLegalReport(): string {
  return `MIV PLATFORM - LEGAL DUE DILIGENCE REPORT
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
================
This legal due diligence report covers corporate structure, compliance status, intellectual property, 
and legal risks associated with the investment opportunity.

CORPORATE STRUCTURE
==================
â€¢ Entity Type: Private Limited Company
â€¢ Jurisdiction: Singapore (favorable for impact investing)
â€¢ Share Structure: Clear cap table with appropriate option pool
â€¢ Board Composition: Balanced with independent directors

COMPLIANCE STATUS
================
â€¢ Regulatory Compliance: Current on all regulatory filings
â€¢ Employment Law: Compliant with local labor regulations
â€¢ Data Privacy: GDPR and local privacy law compliant
â€¢ Anti-Corruption: Robust compliance policies in place

INTELLECTUAL PROPERTY
====================
â€¢ Patents: 3 pending patents for core technology
â€¢ Trademarks: Brand names properly registered
â€¢ Trade Secrets: Adequate protection measures
â€¢ IP Ownership: Clear ownership by company

GEDSI LEGAL FRAMEWORK
====================
â€¢ Diversity Policies: Comprehensive D&I policies documented
â€¢ Accessibility Compliance: WCAG 2.1 AA compliance achieved
â€¢ Equal Pay Certification: Gender pay equity certified
â€¢ Disability Rights: ADA-equivalent compliance in operations

CONTRACTS & AGREEMENTS
=====================
â€¢ Customer Contracts: Standard terms, appropriate liability limits
â€¢ Supplier Agreements: Diverse supplier base, 40% women/minority-owned
â€¢ Employment Contracts: Standard terms with appropriate IP assignment
â€¢ Partnership Agreements: Strategic partnerships properly documented

LEGAL RISKS
==========
â€¢ Litigation Risk: Low - no pending or threatened litigation
â€¢ Regulatory Risk: Medium - evolving regulatory landscape
â€¢ IP Risk: Low - strong IP protection strategy
â€¢ Contract Risk: Low - well-documented agreements

RECOMMENDATIONS
==============
1. Proceed with investment - clean legal structure
2. Implement enhanced GEDSI policy documentation
3. Consider additional IP protection in key markets
4. Regular compliance audits recommended

IRIS+ LEGAL COMPLIANCE
=====================
â€¢ Governance Structure: Meets IRIS+ governance standards
â€¢ Impact Measurement: Legal framework supports impact tracking
â€¢ Stakeholder Rights: Appropriate protections for all stakeholders

This legal analysis supports the investment with minor recommendations for enhanced documentation.

Report prepared by: MIV Legal Analysis Team
Contact: legal@miv.org
`
}

export function generateTechnicalReport(): string {
  return `MIV PLATFORM - TECHNICAL DUE DILIGENCE REPORT
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
================
This technical due diligence report evaluates the venture's technology stack, scalability, 
security posture, and technical team capabilities.

TECHNOLOGY ARCHITECTURE
======================
â€¢ Stack: Modern cloud-native architecture
â€¢ Scalability: Microservices design supports 10x growth
â€¢ Performance: <200ms response times, 99.9% uptime
â€¢ Database: PostgreSQL with proper indexing and optimization

SECURITY ASSESSMENT
==================
â€¢ Data Protection: AES-256 encryption at rest and in transit
â€¢ Access Control: Multi-factor authentication implemented
â€¢ Vulnerability Management: Regular security scans and updates
â€¢ Compliance: SOC 2 Type II ready

ACCESSIBILITY & INCLUSION
=========================
â€¢ WCAG 2.1 AA Compliance: Full accessibility features implemented
â€¢ Multi-language Support: 5 languages supported for diverse markets
â€¢ Offline Capabilities: Works in low-bandwidth environments
â€¢ Mobile Optimization: Progressive web app for mobile access

DEVELOPMENT PRACTICES
====================
â€¢ Code Quality: 95% test coverage, automated testing
â€¢ Version Control: Git with proper branching strategy
â€¢ CI/CD: Automated deployment pipeline
â€¢ Documentation: Comprehensive technical documentation

SCALABILITY ANALYSIS
===================
â€¢ Current Capacity: 10,000 concurrent users
â€¢ Growth Projection: Can scale to 100,000 users with current architecture
â€¢ Performance Benchmarks: Meets enterprise-grade standards
â€¢ Infrastructure: Cloud-native with auto-scaling capabilities

TECHNICAL TEAM
==============
â€¢ CTO Background: 10+ years experience, previous successful exits
â€¢ Development Team: 8 engineers, 50% women, diverse backgrounds
â€¢ Technical Advisory: Strong technical advisory board
â€¢ Skill Gaps: Minor gaps in AI/ML expertise, easily addressable

TECHNOLOGY RISKS
===============
â€¢ Vendor Lock-in: Low - multi-cloud strategy implemented
â€¢ Technical Debt: Low - modern codebase with good practices
â€¢ Scalability Risk: Low - proven architecture patterns
â€¢ Security Risk: Low - enterprise-grade security measures

RECOMMENDATIONS
==============
1. Strong technical foundation supports investment
2. Consider additional AI/ML talent acquisition
3. Implement enhanced monitoring and observability
4. Regular security audits recommended

IRIS+ TECHNICAL METRICS
======================
â€¢ Digital Inclusion: 95% mobile accessibility score
â€¢ Technology Access: Supports low-bandwidth environments
â€¢ Innovation Index: High - proprietary technology advantages

This technical analysis strongly supports the investment with excellent technical fundamentals.

Report prepared by: MIV Technical Analysis Team
Contact: tech@miv.org
`
}

export function generateMarketReport(): string {
  return `MIV PLATFORM - MARKET DUE DILIGENCE REPORT
Generated: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
================
This market due diligence report analyzes the venture's market opportunity, competitive position,
and growth potential in the target markets.

MARKET OPPORTUNITY
=================
â€¢ Total Addressable Market (TAM): $50B globally
â€¢ Serviceable Addressable Market (SAM): $5B in target regions
â€¢ Serviceable Obtainable Market (SOM): $500M realistic capture
â€¢ Market Growth Rate: 25% CAGR over next 5 years

COMPETITIVE LANDSCAPE
====================
â€¢ Direct Competitors: 3 major players identified
â€¢ Competitive Advantage: Strong differentiation through inclusion focus
â€¢ Market Position: Early leader in inclusive technology solutions
â€¢ Barriers to Entry: High - regulatory and relationship requirements

GEDSI MARKET ANALYSIS
====================
â€¢ Women-Led Market Segment: $2B underserved market opportunity
â€¢ Disability-Inclusive Products: 15% market premium achievable
â€¢ Rural Market Penetration: 40% market share potential
â€¢ Youth Engagement: 65% of target demographic under 35

CUSTOMER ANALYSIS
================
â€¢ Customer Acquisition Cost: $150 (industry average: $200)
â€¢ Customer Lifetime Value: $2,500 (strong unit economics)
â€¢ Customer Retention: 85% annual retention rate
â€¢ Market Validation: 500+ pilot customers with positive feedback

GEOGRAPHIC EXPANSION
===================
â€¢ Primary Markets: Thailand, Vietnam, Philippines
â€¢ Secondary Markets: Indonesia, Malaysia, Myanmar
â€¢ Market Entry Strategy: Partnership-first approach
â€¢ Regulatory Environment: Favorable for impact ventures

MARKET RISKS
===========
â€¢ Competition Risk: Medium - established players entering market
â€¢ Regulatory Risk: Low - supportive government policies
â€¢ Economic Risk: Medium - emerging market volatility
â€¢ Technology Risk: Low - proven technology adoption

RECOMMENDATIONS
==============
1. Strong market opportunity supports investment
2. Accelerate geographic expansion strategy
3. Strengthen competitive moats through partnerships
4. Focus on GEDSI differentiation as key advantage

IRIS+ MARKET METRICS
===================
â€¢ Market Reach: 25,000 customers in underserved communities
â€¢ Geographic Coverage: 5 countries in Southeast Asia
â€¢ Market Impact: 15% improvement in financial inclusion metrics

This market analysis strongly supports the investment opportunity with significant growth potential.

Report prepared by: MIV Market Analysis Team
Contact: market@miv.org
`
}
