import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { gedsiScoreClass, RiskBadge, RiskIcon } from "./round-presentation"
import type { InvestmentRound } from "@/app/dashboard/(g3-venture-pipeline)/investment-rounds/libs/types"

export function RoundDetailDialog({ round, open, onOpenChange }: { round: InvestmentRound | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  if (!round) return null
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>{round.company} - {round.roundType}</DialogTitle><DialogDescription>Detailed investment round information with GEDSI insights</DialogDescription></DialogHeader>
    <div className="grid gap-6 md:grid-cols-2"><div className="space-y-4"><div><h4 className="mb-2 font-medium">Round Information</h4><div className="space-y-2 text-sm"><div>Target: {round.targetAmount}</div><div>Raised: {round.raisedAmount}</div><div>Valuation: {round.valuation}</div><div>Ownership: {round.ownership}%</div><div>Lead Investor: {round.leadInvestor}</div><div>Closing Date: {round.closingDate}</div></div></div><div><h4 className="mb-2 font-medium">GEDSI Scores</h4><div className="space-y-2"><div className="flex justify-between"><span>GEDSI Score</span><span className={`font-bold ${gedsiScoreClass(round.gedsiScore)}`}>{round.gedsiScore}</span></div><div className="flex justify-between"><span>Impact Score</span><span className="font-bold text-blue-600">{round.impactScore}</span></div><div className="flex justify-between"><span>Sustainability</span><span className="font-bold text-green-600">{round.sustainabilityScore}</span></div></div></div></div>
      <div className="space-y-4"><div><h4 className="mb-2 font-medium">Impact Metrics</h4><div className="space-y-2 text-sm"><div>Jobs Created: {round.metrics.jobsCreated}</div><div>Communities Served: {round.metrics.communitiesServed}</div><div>Women Leadership: {round.metrics.womenLeadership}%</div><div>Carbon Reduction: {round.metrics.carbonReduction}t CO2</div></div></div><div><h4 className="mb-2 font-medium">AI Insights</h4><div className="space-y-2 text-sm"><div className="flex items-center gap-2"><RiskIcon level={round.aiInsights.riskLevel} /><RiskBadge level={round.aiInsights.riskLevel} /></div><p className="text-muted-foreground">{round.aiInsights.recommendation}</p></div></div></div>
    </div></DialogContent></Dialog>
}
